# Use Node.js image
FROM node:16-alpine

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Expose port 4200
EXPOSE 4200

# Start the frontend development server
CMD ["npm", "start"]
