version: "3.8"

services:
  # Database service
  database:
    container_name: adverity-transformer-challenge-database
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: transformer
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Main backend application
  backend:
    container_name: adverity-transformer-challenge-backend
    build:
      context: ${PWD}/backend/
      dockerfile: Dockerfile.development
    image: adverity-transformer-challenge-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: database
      DATABASE_USER: postgres
      DATABASE_NAME: transformer
    volumes:
      - ${PWD}/backend/:/home/user/backend/:delegated
      - ${PWD}/frontend/:/home/user/frontend/:delegated
    depends_on:
      - database
    restart: on-failure

  # Frontend service for Angular
  frontend:
    container_name: adverity-transformer-challenge-frontend
    image: node:18-alpine
    working_dir: /home/user/frontend
    volumes:
      - ${PWD}/frontend:/home/user/frontend
    ports:
      - "4200:4200"
    command: sh -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0"
    depends_on:
      - backend
    restart: unless-stopped
