# Generated by Django 4.2.16 on 2024-09-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsv',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
